name: Build Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Install Eigen3
      run: sudo apt -y install libeigen3-dev

    - name: Build
      run: cmake -S . -B build --config RelWithDebInfo --target all
